package br.com.techbr.fiscalanalyzer.xml.parser;

import java.math.BigDecimal;
import java.time.Instant;
import java.time.LocalDate;
import java.util.List;

public record ParsedNfe(
        short model,
        String accessKey,
        Integer numeroNota,
        String serie,
        String naturezaOperacao,
        LocalDate issueDate,
        Instant issueDateTime,
        Short ambiente,
        Short finalidadeEmissao,
        Short consumidorFinal,
        Short presencaComprador,
        String operationType,
        String emitCnpj,
        String emitName,
        String emitIe,
        String emitUf,
        String destDocument,
        String destCnpj,
        String destName,
        String destIe,
        String destUf,
        BigDecimal totalProducts,
        BigDecimal totalAmount,
        BigDecimal totalFrete,
        BigDecimal totalDesconto,
        BigDecimal totalOutros,
        BigDecimal totalIpi,
        BigDecimal totalTributos,
        BigDecimal totalIcms,
        BigDecimal totalPis,
        BigDecimal totalCofins,
        String protocoloNumero,
        Integer protocoloStatus,
        String protocoloMotivo,
        Instant protocoloRecebimento,
        String qrCodeUrl,
        String faturaNumero,
        BigDecimal faturaValorOriginal,
        BigDecimal faturaValorDesconto,
        BigDecimal faturaValorLiquido,
        List<ParsedNfePayment> payments,
        List<ParsedNfeDuplicate> duplicates,
        List<ParsedNfeAdditionalInfo> additionalInfos,
        List<ParsedNfeItem> items
) {}
